import React from 'react'
import Head from 'next/head'

export default function Home () {
  return (
    <div>
      <Head>
        <title>Carteira Global - Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Carteira Global - Challenge</h1>
      </main>
    </div>
  )
}
