import React from 'react'
import Head from 'next/head'

import Dashboard from '../presentation/templates/Dashboard'

export default function Home () {
  return (
    <div>
      <Head>
        <title>Carteira Global - Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Dashboard />
      </main>
    </div>
  )
}
